[project]
name = "kolmogorov-lipschitz-algorithm"
version = "0.1.0"
description = "Implementation of the Algorithm described in https://doi.org/10.48550/arXiv.1712.08286"
requires-python = ">=3.13"
dependencies = [
    "gmpy2==2.2.1",
    "intervaltree==3.1.0",
    "matplotlib==3.10.3",
]
